<?php
    session_start();
    if(!isset($_SESSION["login"])){
        header("Location:./login.php");
        exit();
    }
    session_unset();
    session_destroy();
    setcookie("username","",time()-3600);
    setcookie("id","",time()-3600);
    header("Location:./login.php");
    exit();
?>